#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Example.Resource", IsApplication=true)]

namespace Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PagerSlidingTabStrip.Resource.Attribute.dividerColor = global::Example.Resource.Attribute.dividerColor;
			global::PagerSlidingTabStrip.Resource.Attribute.dividerPadding = global::Example.Resource.Attribute.dividerPadding;
			global::PagerSlidingTabStrip.Resource.Attribute.indicatorColor = global::Example.Resource.Attribute.indicatorColor;
			global::PagerSlidingTabStrip.Resource.Attribute.indicatorHeight = global::Example.Resource.Attribute.indicatorHeight;
			global::PagerSlidingTabStrip.Resource.Attribute.scrollOffset = global::Example.Resource.Attribute.scrollOffset;
			global::PagerSlidingTabStrip.Resource.Attribute.shouldExpand = global::Example.Resource.Attribute.shouldExpand;
			global::PagerSlidingTabStrip.Resource.Attribute.tabBackground = global::Example.Resource.Attribute.tabBackground;
			global::PagerSlidingTabStrip.Resource.Attribute.tabPaddingLeftRight = global::Example.Resource.Attribute.tabPaddingLeftRight;
			global::PagerSlidingTabStrip.Resource.Attribute.textAllCaps = global::Example.Resource.Attribute.textAllCaps;
			global::PagerSlidingTabStrip.Resource.Attribute.underlineColor = global::Example.Resource.Attribute.underlineColor;
			global::PagerSlidingTabStrip.Resource.Attribute.underlineHeight = global::Example.Resource.Attribute.underlineHeight;
			global::PagerSlidingTabStrip.Resource.Color.background_tab_pressed = global::Example.Resource.Color.background_tab_pressed;
			global::PagerSlidingTabStrip.Resource.Drawable.pagerslidingtabstrip_background_tab = global::Example.Resource.Drawable.pagerslidingtabstrip_background_tab;
			global::PagerSlidingTabStrip.Resource.String.ApplicationName = global::Example.Resource.String.ApplicationName;
			global::PagerSlidingTabStrip.Resource.String.Hello = global::Example.Resource.String.Hello;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip = global::Example.Resource.Styleable.PagerSlidingTabStrip;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_dividerColor = global::Example.Resource.Styleable.PagerSlidingTabStrip_dividerColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_dividerPadding = global::Example.Resource.Styleable.PagerSlidingTabStrip_dividerPadding;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_indicatorColor = global::Example.Resource.Styleable.PagerSlidingTabStrip_indicatorColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_indicatorHeight = global::Example.Resource.Styleable.PagerSlidingTabStrip_indicatorHeight;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_scrollOffset = global::Example.Resource.Styleable.PagerSlidingTabStrip_scrollOffset;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_shouldExpand = global::Example.Resource.Styleable.PagerSlidingTabStrip_shouldExpand;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_tabBackground = global::Example.Resource.Styleable.PagerSlidingTabStrip_tabBackground;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_tabPaddingLeftRight = global::Example.Resource.Styleable.PagerSlidingTabStrip_tabPaddingLeftRight;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_textAllCaps = global::Example.Resource.Styleable.PagerSlidingTabStrip_textAllCaps;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_underlineColor = global::Example.Resource.Styleable.PagerSlidingTabStrip_underlineColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_underlineHeight = global::Example.Resource.Styleable.PagerSlidingTabStrip_underlineHeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int dividerColor = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int dividerPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int indicatorColor = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int indicatorHeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int scrollOffset = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int shouldExpand = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int tabBackground = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int tabPaddingLeftRight = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int textAllCaps = 2130771978;
			
			// aapt resource value: 0x7f010001
			public const int underlineColor = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int underlineHeight = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background_tab_pressed = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int background_window = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_bottom = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_card = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_tabs = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_tabs_diagonal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int contact = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_user = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher_actionbar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher_chrome = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher_gmail = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher_gmaps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher_gplus = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pagerslidingtabstrip_background_tab = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tabs_pattern = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tabs_pattern_diagonal = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int MyButton = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int action_contact = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int action_settabsfull = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int action_settabsone = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int action_settabsthree = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int action_settabstwo = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int center = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int colors = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int image = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int pager = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int tabs = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_quick_contact = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int action_contact = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBarStyle = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PagerSlidingTabStrip = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 2
			public const int PagerSlidingTabStrip_dividerColor = 2;
			
			// aapt resource value: 5
			public const int PagerSlidingTabStrip_dividerPadding = 5;
			
			// aapt resource value: 0
			public const int PagerSlidingTabStrip_indicatorColor = 0;
			
			// aapt resource value: 3
			public const int PagerSlidingTabStrip_indicatorHeight = 3;
			
			// aapt resource value: 7
			public const int PagerSlidingTabStrip_scrollOffset = 7;
			
			// aapt resource value: 9
			public const int PagerSlidingTabStrip_shouldExpand = 9;
			
			// aapt resource value: 8
			public const int PagerSlidingTabStrip_tabBackground = 8;
			
			// aapt resource value: 6
			public const int PagerSlidingTabStrip_tabPaddingLeftRight = 6;
			
			// aapt resource value: 10
			public const int PagerSlidingTabStrip_textAllCaps = 10;
			
			// aapt resource value: 1
			public const int PagerSlidingTabStrip_underlineColor = 1;
			
			// aapt resource value: 4
			public const int PagerSlidingTabStrip_underlineHeight = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
