#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PagerSlidingTabStrip.Resource", IsApplication=false)]

namespace PagerSlidingTabStrip
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int dividerColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int indicatorColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int indicatorHeight = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int nonSelectedTextColor = 2130771971;
			
			// aapt resource value: 0x7f010008
			public static int scrollOffset = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int shouldExpand = 2130771978;
			
			// aapt resource value: 0x7f010009
			public static int tabBackground = 2130771977;
			
			// aapt resource value: 0x7f010006
			public static int tabDividerPadding = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int tabPaddingLeftRight = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public static int tabTextAllCaps = 2130771979;
			
			// aapt resource value: 0x7f010001
			public static int underlineColor = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int underlineHeight = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int background_tab_pressed = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int pagerslidingtabstrip_background_tab = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int pagerslidingtabstrip_texttab = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PagerSlidingTabStrip = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 2
			public static int PagerSlidingTabStrip_dividerColor = 2;
			
			// aapt resource value: 0
			public static int PagerSlidingTabStrip_indicatorColor = 0;
			
			// aapt resource value: 4
			public static int PagerSlidingTabStrip_indicatorHeight = 4;
			
			// aapt resource value: 3
			public static int PagerSlidingTabStrip_nonSelectedTextColor = 3;
			
			// aapt resource value: 8
			public static int PagerSlidingTabStrip_scrollOffset = 8;
			
			// aapt resource value: 10
			public static int PagerSlidingTabStrip_shouldExpand = 10;
			
			// aapt resource value: 9
			public static int PagerSlidingTabStrip_tabBackground = 9;
			
			// aapt resource value: 6
			public static int PagerSlidingTabStrip_tabDividerPadding = 6;
			
			// aapt resource value: 7
			public static int PagerSlidingTabStrip_tabPaddingLeftRight = 7;
			
			// aapt resource value: 11
			public static int PagerSlidingTabStrip_tabTextAllCaps = 11;
			
			// aapt resource value: 1
			public static int PagerSlidingTabStrip_underlineColor = 1;
			
			// aapt resource value: 5
			public static int PagerSlidingTabStrip_underlineHeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
